# Generated by Django 2.2.2 on 2019-10-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandwagon', '0007_auto_20191001_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
